### PR TITLE
Create dlc_main.html

### PR DESCRIPTION
**Pull request by ztrelease**
A landing page for the digital land charges project

### CODE REVIEW

**Comment by ptrelease** [comment]
Cool.  Do you want me to do your Pull Request? ;-)

**Comment by matthew-shaw** [comment]
Think this has been surpassed by PR #28 
Suggest closing?

**Comment by ztrelease** [comment]
Yup, please do.

**Comment by AndrewGorton** [comment]
Can we close this? It's been hanging around for 43 days at the top of our merge radiator...

**Comment by lendmeapound** [comment]
Kill it Gorton!

**Comment by AndrewGorton** [comment]
Closed as requested above.

**Pull request closed without merging**
